import logging

from fastapi import APIRouter, Depends, Query
from fastapi.responses import PlainTextResponse, RedirectResponse
from sqlalchemy.ext.asyncio import AsyncSession

from app.auth.dependencies import get_current_user
from app.channels.schemas import ChannelRead
from app.core.config import settings
from app.core.database import get_session
from app.core.errors import AppError
from app.instagram.handlers import dispatch_instagram_webhook
from app.instagram.schemas import InstagramOAuthCallbackResponse
from app.instagram.service import MetaService
from app.organizations.models import Organization
from app.organizations.services import ensure_org_member
from app.users.models import User

logger = logging.getLogger(__name__)
router = APIRouter(tags=["instagram"])


@router.get(
    "/integrations/instagram/oauth/login",
    summary="Start Instagram OAuth",
    description="Generates a signed Meta OAuth state for the organization and redirects the user to Meta.",
    response_class=RedirectResponse,
)
async def instagram_oauth_login(
    organization_id: str = Query(description="Organization that will receive the Instagram channel connection."),
    current_user: User = Depends(get_current_user),
    session: AsyncSession = Depends(get_session),
) -> RedirectResponse:
    await ensure_org_member(session, current_user, organization_id)
    oauth_url = MetaService().generate_oauth_url(organization_id=organization_id, user_id=current_user.id)
    return RedirectResponse(oauth_url)


@router.get(
    "/integrations/instagram/oauth/callback",
    response_model=InstagramOAuthCallbackResponse,
    summary="Complete Instagram OAuth",
    description="Exchanges the Meta OAuth code, discovers linked Facebook Pages and Instagram Business Accounts, "
    "and saves active Instagram channel connections.",
)
async def instagram_oauth_callback(
    code: str = Query(description="Authorization code returned by Meta OAuth."),
    state: str = Query(description="Signed OAuth state generated by Sello AI."),
    session: AsyncSession = Depends(get_session),
) -> InstagramOAuthCallbackResponse:
    service = MetaService()
    state_payload = service.decode_oauth_state(state)
    organization_id = state_payload["organization_id"]
    user_id = state_payload["user_id"]

    organization = await session.get(Organization, organization_id)
    user = await session.get(User, user_id)
    if organization is None or user is None:
        raise AppError("Meta OAuth state references an unknown organization.", "META_OAUTH_INVALID_STATE", 400)
    await ensure_org_member(session, user, organization_id)

    short_lived_token = await service.exchange_code(code)
    long_lived_token = await service.get_long_lived_token(short_lived_token)
    pages = await service.get_pages(long_lived_token)
    channels = []
    for page in pages:
        instagram_business = await service.get_instagram_business(page)
        if instagram_business is None:
            continue
        channel = await service.save_channel(
            session,
            organization_id=organization_id,
            page=page,
            instagram_business=instagram_business,
            user_access_token=long_lived_token,
            connected_by_user_id=user_id,
        )
        channels.append(ChannelRead.model_validate(channel))

    logger.info(
        "Completed Instagram OAuth",
        extra={"organization_id": organization_id, "saved_channels": len(channels), "pages": len(pages)},
    )
    return InstagramOAuthCallbackResponse(
        status="connected" if channels else "no_instagram_business_account",
        saved_channels=len(channels),
        channels=channels,
    )


@router.get(
    "/webhooks/instagram",
    response_class=PlainTextResponse,
    summary="Verify Instagram webhook",
    description="Implements Meta webhook verification by echoing the challenge when the verify token matches.",
)
async def verify_instagram_webhook(
    hub_mode: str = Query(alias="hub.mode"),
    hub_verify_token: str = Query(alias="hub.verify_token"),
    hub_challenge: str = Query(alias="hub.challenge"),
) -> str:
    if hub_mode == "subscribe" and hub_verify_token == settings.meta_verify_token:
        return hub_challenge
    raise AppError("Instagram webhook verification failed.", "META_WEBHOOK_VERIFICATION_FAILED", 403)


@router.post(
    "/webhooks/instagram",
    summary="Receive Instagram webhook events",
    description="Receives Instagram DM and comment webhook payloads and dispatches supported event skeletons.",
)
async def instagram_webhook(payload: dict) -> dict[str, object]:
    result = await dispatch_instagram_webhook(payload)
    return {"ok": True, "dispatched": result}
